Fix development environment with D-bus session

diff --git a/bin/test_integration b/bin/test_integration
--- a/bin/test_integration
+++ b/bin/test_integration
@@ -2,15 +2,17 @@
 
 cleanup() {
   echo "Cleaning up..."
-  docker-compose rm --stop --force -v
+  echo "Cleaning up... logs in cleanup.log"
+  docker-compose rm --stop --force
 }
 
+DEBUG="false"
 if [[ "$1" = "--debug" || "$1" = "-d" ]]; then
   DEBUG="true"
   shift
 fi
 
-trap 'echo "ERROR: Test script encountered an error!"; docker-compose logs; cleanup' ERR
+trap 'echo "ERROR: Test script encountered an error!"; docker-compose logs &> cleanup.log; cleanup' ERR
 trap 'cleanup' EXIT
 cleanup
 
@@ -28,6 +30,7 @@ echo "Configuring Conjur..."
 admin_api_key=$(docker-compose exec -T conjur conjurctl role retrieve-key dev:user:admin | tr -d '\r')
 export CONJUR_AUTHN_API_KEY=$admin_api_key
 export PYTHON_KEYRING_BACKEND=keyring.backends.SecretService.Keyring
+export DEBUG=$DEBUG
 conjur_host_port=$(docker-compose port conjur 80)
 conjur_port="${conjur_host_port##*:}"
 
@@ -36,6 +39,7 @@ conjur_port="${conjur_host_port##*:}"
 cat <<ENV > .env
 CONJUR_AUTHN_API_KEY=$admin_api_key
 PYTHON_KEYRING_BACKEND=$PYTHON_KEYRING_BACKEND
+DEBUG=$DEBUG
 ENV
 
 echo "Starting test env..."
@@ -46,7 +50,7 @@ rm -rf $CURRENT_DIR/output/*
 # Hint: '--privileged' is added here otherwise we will get operation
 # not permitted when attempting to do anything related to dbus
 if [[ "$DEBUG" == "true" ]]; then
-  docker-compose exec --privileged test bash
+  docker-compose exec --privileged test /bin/sh -c " /dbus.sh" $@
   exit
 fi
 
